title: Eat Sleep Skate
title_short: ESS Bali
title_long: ESS Bali • Eat Sleep Skate
email: eatsleepskatebali@gmail.com
telephone: +62 361 4720185
handphone: +62 818 05620365
whatsapp: +62 818 05620365
booking_phone: +62 823 39536271
address:  Jl. Sedap Malam, Gg. Kwangen 13, Banjar Bhuana Anyar, Sumerta Kelod, Denpasar Timur, Bali 80237
short_address: Jl. Sedap Malam, Gg. Kwangen 13, Banjar Bhuana Anyar, Sanur.
description: > # this means to ignore newlines until "baseurl:"
  Bungalows, pool, restaurant, and a skate bowl in Bali. Located near Sanur beach. We designed it all ourselves in harmony with it’s peaceful green environment. Open skateboarding sessions on weekends 3pm to 9pm. Reserved for our guest everyday. A place where you can Eat Sleep and Skate.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://essbali.com"
github_url: "https://toybreaker.github.io/ess/"
repository: toybreaker/ess
instagram: eatsleepskatebali
instagram_tag: https://www.instagram.com/explore/tags/essbali
facebook: essbali
twitter: essbali
twitter_creator: rokmatwit
booking: http://booking.com/e682abb837ed8f61f
tripadvisor: http://www.tripadvisor.com/Hotel_Review-g297700-d7732966-Reviews-Eat_Sleep_Skate-Sanur_Denpasar_Bali.html
preview_image: /home/01-20161206_photo_rokma_MG_8406.jpg
google:
  youtube: UCptyllNdDP7Cx_3wHwKU8-Q
  analytics: UA-89049941-1
  maps: https://goo.gl/maps/pPpJSdKjMsn
  verification: Rt71Q1qGvbUviohh6n8KmtRoGUd-XeuuuKLBjCMvHO8

# booking service
booking_link: https://www.beds24.com/booking.php?propid=39641&referer=EatSleepSkate+Web+Site
newsletter_link: http://eepurl.com/cHnYk1

# instuff
userId: '1642269704'
clientId: 'bfa7b626c0a644d99cb87002b24b3765'
accessToken: '1642269704.bfa7b62.e7ddecba818e4f7eaf28862aea5acb1c'

# Build settings
markdown: kramdown
gems:
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-feed
